//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyJoyResume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EJ_MY_RESUME652145
    {
        public int MR_ID { get; set; }
        public int MR_RESUMEID { get; set; }
        public string MR_TITLE { get; set; }
        public int MR_ITEMID { get; set; }
        public int MR_MEMBER_ID { get; set; }
        public string MR_JSON { get; set; }
        public System.DateTime MR_CREAT_TIME { get; set; }
        public bool MR_DEL { get; set; }
    }
}
