//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyJoyResume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EJ_RESUME_BANK547852
    {
        public int RB_ID { get; set; }
        public int RB_ITEMID { get; set; }
        public string RB_CONTENT { get; set; }
        public string RB_LANGUAGE { get; set; }
        public string RB_COLOR { get; set; }
        public string RB_FONT_NAME { get; set; }
        public string RB_FONT_SIZE { get; set; }
        public string RB_FONT_HEIGHT { get; set; }
        public string RB_FONT_TYPE { get; set; }
        public string RB_RESUME_SOFT { get; set; }
        public string RB_MODEL_MARGIN { get; set; }
        public int RB_COUNT { get; set; }
    }
}
