//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyJoyResume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EJ_USER241856
    {
        public int U_ID { get; set; }
        public Nullable<int> U_MEMBER_ID { get; set; }
        public string U_MAIL { get; set; }
        public string U_MOBILE { get; set; }
        public string U_NICK_NAME { get; set; }
        public string U_PWD { get; set; }
        public int U_TYPE { get; set; }
        public bool U_DEL { get; set; }
        public string U_IMG { get; set; }
        public System.DateTime U_CREAT_TIME { get; set; }
        public string U_LOGIN_IP { get; set; }
        public System.DateTime U_LOGIN_TIME { get; set; }
        public int U_LOGIN_ERROR { get; set; }
        public string U_SECRETKEY { get; set; }
        public bool U_EMAIL_CHECK { get; set; }
        public bool U_MOBILE_CHECK { get; set; }
    }
}
